---

- hosts: raspberrypi
  tasks:
    - name: Add user enver
      user:
        name: enver
        append: yes
        groups: sudo
        shell: /bin/bash
      become: yes
    - name: Add public SSH keys for enver
      authorized_key:
        key: |
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJLcJhj6RAu2MV4qkLnQvEMjpC0+u8wNUXFN4C0mqIK1 enver@desktop-enver
        user: enver
      become: yes
    - name: Ensure sudoers can sudo passwordless
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo   ALL=(ALL:ALL) NOPASSWD:ALL'
        validate: '/usr/sbin/visudo -cf %s'
      become: yes
      notify: restart sshd
    - name: Disable SSH password login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^(#\s*)?PasswordAuthentication '
        line: "PasswordAuthentication no"
      become: yes
      notify: restart sshd

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
      become: yes

